#!/bin/bash

echo "========================================="
echo "Quick Public Access Options for Liftover"
echo "========================================="
echo ""
echo "Option 1: Use localtunnel (no account needed):"
echo "  npx localtunnel --port 3000"
echo ""
echo "Option 2: Use serveo.net (SSH tunnel, no install):"
echo "  ssh -R 80:localhost:3000 serveo.net"
echo ""
echo "Option 3: Use bore.pub (simple tunnel):"
echo "  npx bore-cli local 3000 --to bore.pub"
echo ""
echo "Option 4: Setup ngrok (free account):"
echo "  1. Sign up at: https://dashboard.ngrok.com/signup"
echo "  2. Get your authtoken from: https://dashboard.ngrok.com/get-started/your-authtoken"
echo "  3. Run: ngrok config add-authtoken YOUR_TOKEN"
echo "  4. Then: ngrok http 3000"
echo ""
echo "========================================="